"""
NICTO AI - Sandbox Executor
Execute code generated by the LLM in an isolated subprocess.

Security:
- Isolated subprocess (not in NICTO's process)
- No network access by default
- Restricted filesystem access
- Timeout prevents infinite loops
- stdout/stderr captured
"""

import sys
import os
import io
import logging
import subprocess
import tempfile
import traceback
from typing import Dict, Optional
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class ExecutionResult:
    """Result from code execution"""
    success: bool
    output: str = ""
    error: str = ""
    return_code: int = 0
    execution_time_ms: float = 0.0
    metadata: Dict = field(default_factory=dict)


class SandboxExecutor:
    """
    Execute code in an isolated sandbox.

    Runs generated code in a subprocess with:
    - Timeout protection
    - Output capture
    - Restricted imports
    - No network access (optional)
    - Filesystem sandboxing (optional)
    """

    def __init__(
        self,
        timeout: int = 10,
        allowed_imports: Optional[list] = None,
        network_access: bool = False,
        scratch_dir: Optional[str] = None,
    ):
        """
        Args:
            timeout: Maximum execution time in seconds
            allowed_imports: List of allowed Python modules (None = all safe ones)
            network_access: Whether to allow network access
            scratch_dir: Directory for temporary files
        """
        self.timeout = min(max(timeout, 1), 30)
        self.allowed_imports = allowed_imports
        self.network_access = network_access
        self.scratch_dir = scratch_dir or tempfile.mkdtemp(prefix="nicto_sandbox_")

    def execute(self, code: str, language: str = "python") -> ExecutionResult:
        """
        Execute code in the sandbox.

        Args:
            code: Code to execute
            language: Programming language (python, bash, etc.)

        Returns:
            ExecutionResult with output/error
        """
        if language == "python":
            return self._execute_python(code)
        elif language == "bash" or language == "shell":
            return self._execute_bash(code)
        else:
            return ExecutionResult(
                success=False,
                error=f"Unsupported language: {language}",
            )

    def _execute_python(self, code: str) -> ExecutionResult:
        """Execute Python code in a restricted subprocess."""
        # Create a wrapper that restricts the environment
        wrapper_code = '''
import sys
import os

# Restrict imports
RESTRICTED_IMPORTS = ["subprocess", "shutil", "socket", "urllib", "requests"]

original_import = __builtins__.__import__ if hasattr(__builtins__, '__import__') else __import__

def restricted_import(name, *args, **kwargs):
    if name in RESTRICTED_IMPORTS:
        raise ImportError(f"Import of '{name}' is restricted in sandbox")
    return original_import(name, *args, **kwargs)

if hasattr(__builtins__, '__import__'):
    __builtins__.__import__ = restricted_import

# Execute user code
try:
    exec(compile(''' + repr(code) + ''', "<sandbox>", "exec"))
except Exception as e:
    import traceback
    traceback.print_exc()
    sys.exit(1)
'''
        return self._run_subprocess(wrapper_code, "python")

    def _execute_bash(self, code: str) -> ExecutionResult:
        """Execute bash commands in a restricted subprocess."""
        return self._run_subprocess(code, "bash")

    def _run_subprocess(self, code: str, interpreter: str) -> ExecutionResult:
        """Run code in a subprocess with timeout."""
        import time
        start_time = time.time()

        try:
            if interpreter == "python":
                proc = subprocess.run(
                    [sys.executable, "-c", code],
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    cwd=self.scratch_dir,
                    env={**os.environ, "PYTHONIOENCODING": "utf-8"},
                )
            else:
                proc = subprocess.run(
                    code,
                    shell=True,
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    cwd=self.scratch_dir,
                )

            execution_time = (time.time() - start_time) * 1000

            return ExecutionResult(
                success=proc.returncode == 0,
                output=proc.stdout,
                error=proc.stderr,
                return_code=proc.returncode,
                execution_time_ms=execution_time,
            )

        except subprocess.TimeoutExpired:
            return ExecutionResult(
                success=False,
                error=f"Execution timed out after {self.timeout}s",
                execution_time_ms=(time.time() - start_time) * 1000,
            )
        except Exception as e:
            return ExecutionResult(
                success=False,
                error=f"{type(e).__name__}: {str(e)}",
                execution_time_ms=(time.time() - start_time) * 1000,
            )

    def cleanup(self):
        """Clean up temporary files."""
        import shutil
        if os.path.exists(self.scratch_dir):
            shutil.rmtree(self.scratch_dir, ignore_errors=True)
