"""
NICTO AI - Sandbox Executor
Execute code generated by the LLM in an isolated subprocess.

Security:
- Isolated subprocess (not in NICTO's process)
- Restricted Python imports (os, subprocess, socket, etc.)
- Bash execution restricted to safe commands only
- Timeout prevents infinite loops
- stdout/stderr captured
"""

import sys
import os
import io
import logging
import subprocess
import tempfile
import traceback
from typing import Dict, Optional
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)

# Python modules that give full system access - BLOCKED
DANGEROUS_IMPORTS = [
    "subprocess", "shutil", "socket", "urllib", "requests",
    "os", "pathlib", "ctypes", "multiprocessing", "threading",
    "signal", "pickle", "marshal", "shelve", "sqlite3",
    "http", "smtplib", "ftplib", "telnetlib", "xmlrpc",
    "importlib", "code", "codeop", "compileall",
]

# Bash commands that are SAFE to run
SAFE_BASH_COMMANDS = [
    "echo", "printf", "date", "whoami", "pwd", "ls", "cat", "head", "tail",
    "wc", "grep", "awk", "sed", "sort", "uniq", "tr", "cut", "diff",
    "find", "file", "stat", "du", "df", "free", "uname", "uptime",
    "env", "printenv", "true", "false", "test", "[", "let",
    "expr", "seq", "yes", "sleep", "which", "type",
    "python3", "python", "node", "jq",
]

# Bash commands that are DANGEROUS - BLOCKED
DANGEROUS_BASH_COMMANDS = [
    "rm", "rmdir", "mv", "cp", "chmod", "chown", "chgrp",
    "dd", "mkfs", "fdisk", "mount", "umount",
    "sudo", "su", "passwd", "useradd", "userdel", "usermod",
    "kill", "killall", "pkill", "nohup", "bg", "fg",
    "wget", "curl", "ssh", "scp", "rsync", "nc", "ncat",
    "iptables", "firewall-cmd", "ufw",
    "systemctl", "service", "init",
    "crontab", "at", "batch",
    "docker", "kubectl", "helm",
    "tar", "zip", "unzip", "gzip", "gunzip", "bzip2",
    "git", "svn", "hg",
    "apt", "apt-get", "yum", "dnf", "pacman", "brew",
    "pip", "npm", "yarn", "cargo",
    "bash", "sh", "zsh", "fish", "csh", "ksh",
    "eval", "exec", "source",
    "reboot", "shutdown", "halt", "poweroff",
    # Windows dangerous commands
    "del", "rd", "format", "diskpart", "ren", "erase",
    "taskkill", "net", "reg", "sc", "shutdown", "rundll32",
    "attrib", "icacls", "takeown",
    "cmd", "powershell", "pwsh",
]


@dataclass
class ExecutionResult:
    """Result from code execution"""
    success: bool
    output: str = ""
    error: str = ""
    return_code: int = 0
    execution_time_ms: float = 0.0
    metadata: Dict = field(default_factory=dict)


class SandboxExecutor:
    """
    Execute code in an isolated sandbox.

    Runs generated code in a subprocess with:
    - Timeout protection
    - Output capture
    - Restricted Python imports (os, subprocess, socket, etc.)
    - Bash restricted to safe commands only
    - Filesystem sandboxing (scratch directory)
    """

    def __init__(
        self,
        timeout: int = 10,
        allowed_imports: Optional[list] = None,
        network_access: bool = False,
        scratch_dir: Optional[str] = None,
    ):
        self.timeout = min(max(timeout, 1), 30)
        self.allowed_imports = allowed_imports
        self.network_access = network_access
        self.scratch_dir = scratch_dir or tempfile.mkdtemp(prefix="nicto_sandbox_")

    def execute(self, code: str, language: str = "python") -> ExecutionResult:
        if language == "python":
            return self._execute_python(code)
        elif language in ("bash", "shell"):
            return self._execute_bash(code)
        else:
            return ExecutionResult(
                success=False,
                error=f"Unsupported language: {language}",
            )

    def _execute_python(self, code: str) -> ExecutionResult:
        """Execute Python code in a restricted subprocess."""
        dangerous = ", ".join(f'"{m}"' for m in DANGEROUS_IMPORTS)
        wrapper_code = f'''
import sys

RESTRICTED_IMPORTS = [{dangerous}]

_original_import = __builtins__.__import__ if hasattr(__builtins__, "__import__") else __import__

def _restricted_import(name, *args, **kwargs):
    for blocked in RESTRICTED_IMPORTS:
        if name == blocked or name.startswith(blocked + "."):
            raise ImportError(f"Import of \'{{name}}\' is restricted in sandbox")
    return _original_import(name, *args, **kwargs)

if hasattr(__builtins__, "__import__"):
    __builtins__.__import__ = _restricted_import

# Also block dangerous builtins
if hasattr(__builtins__, "open"):
    _real_open = __builtins__.open
    def _safe_open(path, *args, **kwargs):
        path_str = str(path)
        if any(x in path_str for x in ["/etc/", "/proc/", "/sys/", "/dev/", "~/.ssh", "/root"]):
            raise PermissionError(f"Access to {{path_str}} is restricted")
        return _real_open(path, *args, **kwargs)
    __builtins__.open = _safe_open

try:
    exec(compile({repr(code)}, "<sandbox>", "exec"))
except Exception:
    import traceback
    traceback.print_exc()
    sys.exit(1)
'''
        return self._run_subprocess(wrapper_code, "python")

    def _execute_bash(self, code: str) -> ExecutionResult:
        """Execute bash commands with safety restrictions."""
        # Check for dangerous commands
        code_lower = code.strip().lower()
        for cmd in DANGEROUS_BASH_COMMANDS:
            # Match command at start of line or after |, ;, &, $(, `
            if (code_lower.startswith(cmd + " ") or
                code_lower.startswith(cmd + "\t") or
                code_lower == cmd or
                f"| {cmd}" in code_lower or
                f"; {cmd}" in code_lower or
                f"&& {cmd}" in code_lower or
                f"$({cmd}" in code_lower or
                f"`{cmd}" in code_lower):
                return ExecutionResult(
                    success=False,
                    error=f"Blocked: '{cmd}' is not allowed in sandbox. Safe commands: {', '.join(SAFE_BASH_COMMANDS[:10])}...",
                )

        # Wrap in restricted bash
        restricted_code = f'''
set -e
set -o pipefail
ulimit -t {self.timeout}
ulimit -f 1024
cd {self.scratch_dir}
{code}
'''
        return self._run_subprocess(restricted_code, "bash")

    def _run_subprocess(self, code: str, interpreter: str) -> ExecutionResult:
        """Run code in a subprocess with timeout."""
        import time
        start_time = time.time()

        try:
            env = {
                **os.environ,
                "PYTHONIOENCODING": "utf-8",
                "PYTHONDONTWRITEBYTECODE": "1",
            }

            if interpreter == "python":
                proc = subprocess.run(
                    [sys.executable, "-c", code],
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    cwd=self.scratch_dir,
                    env=env,
                )
            else:
                proc = subprocess.run(
                    ["cmd", "/c", code],
                    capture_output=True,
                    text=True,
                    timeout=self.timeout,
                    cwd=self.scratch_dir,
                    env=env,
                )

            execution_time = (time.time() - start_time) * 1000

            return ExecutionResult(
                success=proc.returncode == 0,
                output=proc.stdout[:10000],  # Cap output
                error=proc.stderr[:5000],
                return_code=proc.returncode,
                execution_time_ms=execution_time,
            )

        except subprocess.TimeoutExpired:
            return ExecutionResult(
                success=False,
                error=f"Execution timed out after {self.timeout}s",
                execution_time_ms=(time.time() - start_time) * 1000,
            )
        except Exception as e:
            return ExecutionResult(
                success=False,
                error=f"{type(e).__name__}: {str(e)}",
                execution_time_ms=(time.time() - start_time) * 1000,
            )

    def cleanup(self):
        """Clean up temporary files."""
        import shutil
        if os.path.exists(self.scratch_dir):
            shutil.rmtree(self.scratch_dir, ignore_errors=True)
